name: Run Cypress Tests

on: 
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Steps
        run: echo "{markdown content}" >> $GITHUB_STEP_SUMMARY
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npx cypress run
